<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Send an Email | Simple Email App</title>
    <?php echo $this->partial('partials/css.phtml') ?>
</head>

<body>
    <?php echo $this->partial('partials/header.phtml') ?>

    <div class="container mt-5">
        <div class="col-6 m-auto">
            <h2 class="mb-4">Send an Email</h2>

            <!-- Messages -->
            <?php if (isset($this->messages['success'])) : ?>
                <div class="alert alert-success" role="alert">
                    <?php echo $this->messages['success'][0]; ?>
                </div>
            <?php elseif (isset($this->messages['error'])) : ?>
                <div class="alert alert-danger" role="alert">
                    <?php echo $this->messages['error'][0]; ?>
                </div>
            <?php endif; ?>

            <form action="<?php echo $this->url(['action' => 'send-email']); ?>" method="POST">
                <div class="form-group">
                    <label for="name">Name</label>
                    <input type="text" class="form-control" id="name" name="name" placeholder="Enter name" required>
                </div>
                <div class="form-group mt-3">
                    <label for="email">Email</label>
                    <input type="email" class="form-control" id="email" name="email" placeholder="Enter email" required>
                </div>
                <div class="form-group mt-3">
                    <label for="phone">Phone (Optional)</label>
                    <input type="text" class="form-control" id="phone" name="phone" placeholder="Enter phone number">
                </div>
                <div class="form-group mt-3">
                    <label for="emailContent">Email Content</label>
                    <div id="email-content" style="height: 200px;" class="form-control"></div>
                    <input type="hidden" name="email-content" id="email-content-input">
                </div>

                <div class="form-group mt-3 text-end">
                    <button type="submit" class="btn btn-primary">Send Email</button>
                </div>
            </form>
        </div>
    </div>

    <?php echo $this->partial('partials/footer.phtml') ?>
    <?php echo $this->partial('partials/js.phtml') ?>
</body>

</html>