<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sent Emails | Simple Email App</title>
    <?php echo $this->partial('partials/css.phtml') ?>
</head>

<body>
    <?php echo $this->partial('partials/header.phtml') ?>

    <div class="container mt-5">
        <div class="col-6 m-auto">
            <h2 class="mb-4">Sent Emails</h2>

            <div class="d-flex flex-column flex-md-row p-4 gap-4 py-md-3 align-items-center justify-content-start">
                <div class="list-group">
                    <?php foreach ($this->sentEmails as $sentEmail) : ?>
                        <a href="#" class="list-group-item list-group-item-action d-flex gap-3 py-3" aria-current="true" data-bs-toggle='modal' data-bs-target='#modal-<?php echo $sentEmail['id']; ?>'>
                            <img src="assets/img/email.svg" alt="email icon" width="32" height="32" class="rounded-circle flex-shrink-0">
                            <div class="d-flex gap-2 w-100 justify-content-between">
                                <div>
                                    <h6 class="mb-0">
                                        To: <?php echo $this->escape($sentEmail['name']); ?>
                                        <?php echo $this->escape('<' . $sentEmail['email'] . '>'); ?>
                                    </h6>
                                    <p class="mb-0 opacity-75">
                                        <?php echo (strlen($sentEmail['email_content']) > 30) ?
                                            substr($this->escape($sentEmail['email_content']), 0, 30) . ' ...' :
                                            $this->escape($sentEmail['email_content']);
                                        ?>
                                    </p>
                                </div>
                                <small class="opacity-50 text-nowrap">
                                    <?php
                                    $createdAt = new DateTime($sentEmail['created_at']);
                                    echo $this->escape($createdAt->format('m/d/Y') . ' at ' . $createdAt->format('H\hi\m\i\n'));
                                    ?>
                                </small>
                            </div>
                        </a>
                        <div class="modal fade" data-bs-backdrop="static" data-bs-keyboard="false"
                            id="modal-<?php echo $sentEmail['id']; ?>">
                            <div class="modal-dialog modal-dialog-centered">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title">
                                            Email Information
                                        </h5>
                                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                    </div>
                                    <div class="modal-body">
                                        <div>
                                            To:
                                            <span class="text-primary">
                                                <?php echo $this->escape($sentEmail['name']); ?>
                                            </span>
                                            <?php echo $this->escape('<' . $sentEmail['email'] . '>'); ?>
                                        </div>
                                        <div>
                                            Sent: 
                                            <span class="text-primary">
                                                <?php echo $this->escape($createdAt->format('m/d/Y') . ' at ' . $createdAt->format('H\hi\m\i\n')); ?>
                                            </span>
                                        </div>
                                        <div class="mt-3">
                                            <h6>Email content</h6>
                                            <div class="p-3 bg-light border rounded">
                                                <?php echo $this->escape($sentEmail['email_content']); ?>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    <?php endforeach; ?>
                </div>
            </div>
        </div>
    </div>

    <?php echo $this->partial('partials/footer.phtml') ?>
    <?php echo $this->partial('partials/js.phtml') ?>
</body>

</html>