<div class="container">
    <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
        <div class="col-md-4 d-flex align-items-center">
            <a href="/" class="mb-3 me-2 mb-md-0 text-body-secondary text-decoration-none lh-1">
                <img src="https://global-uploads.webflow.com/6341448fda79c92372b010a4/63502c47c8e7bdfa7c25aefe_swapcardLogo.svg" alt="Swapcard logo">
            </a>
            <span class="mb-3 mb-md-0 text-body-secondary">© 2023 Swapcard</span>
        </div>
        <div class="col-md-8 text-end">
            <i>Created by</i>
            <a href="https://github.com/felipefcampelo" target="_blank">Felipe Campelo</a>
        </div>
    </footer>
</div>